--------------------------------------------------------
--  DDL para Tabla DOCTOFOTOGRAFICO
--------------------------------------------------------

  CREATE TABLE DOCTOFOTOGRAFICO 
   ( FOLIO NUMBER, 
	 CLASIFICACION NUMBER,
     AUTOR VARCHAR2(50),
	 COMENTARIO VARCHAR2(100), 
	 FECHA_CREACION DATE,
     FECHA_MODIFICACION DATE,
     CONSTRAINT DOCTOFOTOGRAFICO_PK PRIMARY KEY (FOLIO),
     CONSTRAINT FK_CAT_ALBUM_DOCTO FOREIGN KEY (CLASIFICACION) REFERENCES CAT_ALBUM(CLASIFICACION)
    );
 