INSERT INTO CAT_ALBUM (CLASIFICACION, NOMBRE_CLASIFICACION) VALUES (1,'AFRICAN FIREFINCH')
INSERT INTO CAT_ALBUM (CLASIFICACION, NOMBRE_CLASIFICACION) VALUES (2,'ALBATROSS');
INSERT INTO CAT_ALBUM (CLASIFICACION, NOMBRE_CLASIFICACION) VALUES (3,'RUBY THROATED HUMMINGBIRD');
INSERT INTO CAT_ALBUM (CLASIFICACION, NOMBRE_CLASIFICACION) VALUES (4,'RUFOUS KINGFISHER');
INSERT INTO CAT_ALBUM (CLASIFICACION, NOMBRE_CLASIFICACION) VALUES (5,'ROBIN');
INSERT INTO CAT_ALBUM (CLASIFICACION, NOMBRE_CLASIFICACION) VALUES (6,'SPANGLED COTINGA');
INSERT INTO CAT_ALBUM (CLASIFICACION, NOMBRE_CLASIFICACION) VALUES (7,'TRUMPTER SWAN');
INSERT INTO CAT_ALBUM (CLASIFICACION, NOMBRE_CLASIFICACION) VALUES (8,'TURQUOISE MOTMOT');
INSERT INTO CAT_ALBUM (CLASIFICACION, NOMBRE_CLASIFICACION) VALUES (9,'WHITE CHEEKED TURACO');
INSERT INTO CAT_ALBUM (CLASIFICACION, NOMBRE_CLASIFICACION) VALUES (10,'WILD TURKEY');
INSERT INTO CAT_ALBUM (CLASIFICACION, NOMBRE_CLASIFICACION) VALUES (11,'WILSONS BIRD OF PARADISE');
INSERT INTO CAT_ALBUM (CLASIFICACION, NOMBRE_CLASIFICACION) VALUES (12,'WOOD DUCK');
commit