INSERT INTO FOTOGRAFIA(CODIGO, DESCRIPCION, CLASIFICACION) VALUES (11,'Vivos colores',1);
INSERT INTO FOTOGRAFIA(CODIGO, DESCRIPCION, CLASIFICACION) VALUES (12,'Amistoso',1);
INSERT INTO FOTOGRAFIA(CODIGO, DESCRIPCION, CLASIFICACION) VALUES (31,'Hermoso vuelo',3);

commit

