SET SERVEROUTPUT ON;
create or replace PROCEDURE opcionesDoctoC( --Opcion C Consulta
FOL in	DOCTOFOTOGRAFICO.FOLIO%TYPE)
IS
  -- Declaración de variables locales
CLASIF DOCTOFOTOGRAFICO.CLASIFICACION%type;
AUT DOCTOFOTOGRAFICO.AUTOR%type;
COMENT DOCTOFOTOGRAFICO.COMENTARIO%type;
FCREACION DOCTOFOTOGRAFICO.FECHA_CREACION%type;
FMODIFIC  DOCTOFOTOGRAFICO.FECHA_MODIFICACION%type;
  BEGIN
  -- Instrucciones de ejecución
    BEGIN
        SELECT CLASIFICACION,AUTOR,COMENTARIO,FECHA_CREACION,FECHA_MODIFICACION 
        INTO CLASIF,AUT,COMENT,FCREACION,FMODIFIC
        FROM DOCTOFOTOGRAFICO where FOLIO = FOL;
        commit;
        DBMS_OUTPUT.PUT_LINE('Consulta Documento');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Upps hubo un ERROR');
    END;
    
END;
