SET SERVEROUTPUT ON;
create or replace PROCEDURE OPCIONESDOCTO(--OPCION IN CHAR,  --A Alta, B Borrado, C Consulta, M Modificacion 
FOL in	DOCTOFOTOGRAFICO.FOLIO%TYPE,
CLASIF	in DOCTOFOTOGRAFICO.CLASIFICACION%TYPE,
AUT	in DOCTOFOTOGRAFICO.AUTOR%TYPE,
COMEN in DOCTOFOTOGRAFICO.COMENTARIO%TYPE
)
IS
  -- Declaración de variables locales
  
  BEGIN
  -- Instrucciones de ejecución
    BEGIN
        INSERT INTO DOCTOFOTOGRAFICO(FOLIO,CLASIFICACION,AUTOR,COMENTARIO) VALUES (FOL,CLASIF,AUT,COMEN);
        commit;
        DBMS_OUTPUT.PUT_LINE('Documento dado de alta');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Upps hubo un ERROR');
    END;
    
END;
